<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResourceRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends EntityRepository
{
    public function getLastVersion()
    {
//        return $this->createQueryBuilder('v')
//            ->select('v')
//            ->orderBy('v.version.')
//            ->getQuery()
//            ->getSingleScalarResult();
    }
}
